extends Node
var generated_bars = []
##this is where bars generated by the slot machine are stored and can be accessed for arrangement



#i basically copied the playing logic from the composing screen.
#if we were true super devs we would extract this into a separate script that gets called by both the composing screen and here
#as the code is the same
var bpm = 120.0
##turns real seconds into musical time
func beat_duration():
	return 60.0 / bpm

const NOTES = ["C", "D", "E", "G", "A", "C2"]

var sounds = {}
var player: AudioStreamPlayer

func _ready():
	player = AudioStreamPlayer.new()
	add_child(player)
	sounds["C"]  = load("res://assets/sounds/notes/C.wav")
	sounds["D"]  = load("res://assets/sounds/notes/D.wav")
	sounds["E"]  = load("res://assets/sounds/notes/E.wav")
	sounds["G"]  = load("res://assets/sounds/notes/G.wav")
	sounds["A"]  = load("res://assets/sounds/notes/A.wav")
	sounds["C2"] = load("res://assets/sounds/notes/C2.wav")

func play_bar(bar):
	for beat in bar:
		for note in beat:
			var pitch = note[0]
			var duration = note[1]
			
			if pitch != "REST":
				player.stream = sounds[pitch]
				player.play()
				
			await get_tree().create_timer(duration * beat_duration()).timeout

func play_bars(bars):
	for bar in bars:
		print (bar)
		await play_bar(bar)
