extends Node
var generated_bars = []
##this is where bars generated by the slot machine are stored and can be accessed for arrangement

const CROTCHET = 1.0
const QUAVER = 0.5
#i basically copied the playing logic from the composing screen.
#if we were true super devs we would extract this into a separate script that gets called by both the composing screen and here
#as the code is the same
var bpm = 120.0
##turns real seconds into musical time
func beat_duration():
	return 60.0 / bpm

const NOTES = ["C", "D", "E", "G", "A", "C2"]

var sounds = {}
var current_bar = []
var player: AudioStreamPlayer

func _ready():
	player = AudioStreamPlayer.new()
	add_child(player)
	sounds["C"]  = load("res://assets/sounds/notes/C.wav")
	sounds["D"]  = load("res://assets/sounds/notes/D.wav")
	sounds["E"]  = load("res://assets/sounds/notes/E.wav")
	sounds["G"]  = load("res://assets/sounds/notes/G.wav")
	sounds["A"]  = load("res://assets/sounds/notes/A.wav")
	sounds["C2"] = load("res://assets/sounds/notes/C2.wav")

func generate_beat():
	##range affect how often certain length of notes appear. We don't want too many rests.
	var roll = randi_range(1, 100)
	##Crotchet note
	if roll <= 40:
		return [[NOTES.pick_random(),CROTCHET]]
	##Crotchet rest
	elif roll <=50:
		return [["REST",CROTCHET]]
	##Quaver note + quaver rest
	elif roll <=60: 
		return [[NOTES.pick_random(),QUAVER],["REST",QUAVER]]
	##Quaver rest + quaver note
	elif roll <=70:
		return [["REST",QUAVER],[NOTES.pick_random(),QUAVER]]
	##Quaver note + quaver note
	else:
		return [[NOTES.pick_random(),QUAVER],[NOTES.pick_random(),QUAVER]]

func generate_bar():
	var bar = []
	for i in range(4):
		bar.append(generate_beat())
	return bar
	
func beat_to_key(beat):
	if beat.size() == 1:
		return "crot_" + note_to_sprite_name(beat[0][0])
	else:
		return "quav_" + note_to_sprite_name(beat[0][0]) + note_to_sprite_name(beat[1][0])
		
func note_to_sprite_name(note):
	match note:
		"C": return "c"
		"D": return "d"
		"E": return "e"
		"G": return "g"
		"A": return "a"
		"C2": return "c2"
		"REST": return "r"
		
func play_bar(bar):
	for beat in bar:
		await play_beat(beat)

func play_bars(bars):
	for bar in bars:
		print (bar)
		await play_bar(bar)
		
func play_beat(beat):
	for note in beat:
		play_note(note)
		var duration = note[1]
		await get_tree().create_timer(duration * beat_duration()).timeout
		
func play_note(note):
		var pitch = note[0]
		if pitch != "REST":
			player.stream = sounds[pitch]
			player.play()
