extends Node
var generated_bars = []
##this is where bars generated by the slot machine are stored and can be accessed for arrangement

const CROTCHET = 1.0
const QUAVER = 0.5
#i basically copied the playing logic from the composing screen.
#if we were true super devs we would extract this into a separate script that gets called by both the composing screen and here
#as the code is the same
var bpm = 120.0
##turns real seconds into musical time
func beat_duration():
	return 60.0 / bpm

const NOTES = ["C", "D", "E", "G", "A", "C2"]

var sounds = {}
var beat_sprites = {}
var current_bar = []
var player: AudioStreamPlayer

func _ready():
	player = AudioStreamPlayer.new()
	add_child(player)
	sounds["C"]  = load("res://assets/sounds/notes/C.wav")
	sounds["D"]  = load("res://assets/sounds/notes/D.wav")
	sounds["E"]  = load("res://assets/sounds/notes/E.wav")
	sounds["G"]  = load("res://assets/sounds/notes/G.wav")
	sounds["A"]  = load("res://assets/sounds/notes/A.wav")
	sounds["C2"] = load("res://assets/sounds/notes/C2.wav")
	
	beat_sprites["crot_c"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_c.png")
	beat_sprites["crot_d"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_d.png")
	beat_sprites["crot_e"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_e.png")
	beat_sprites["crot_g"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_g.png")
	beat_sprites["crot_a"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_a.png")
	beat_sprites["crot_c2"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_c2.png")
	beat_sprites["crot_r"] = load("res://assets/sprites/SLOTMACHINEnotes/crot_r.png")
	
	beat_sprites["quav_cc"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_cc.png")
	beat_sprites["quav_cd"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_cd.png")
	beat_sprites["quav_ce"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ce.png")
	beat_sprites["quav_cg"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_cg.png")
	beat_sprites["quav_ca"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ca.png")
	beat_sprites["quav_cc2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_cc2.png")
	beat_sprites["quav_cr"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_cr.png")
	
	beat_sprites["quav_dc"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_dc.png")
	beat_sprites["quav_dd"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_dd.png")
	beat_sprites["quav_de"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_de.png")
	beat_sprites["quav_dg"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_dg.png")
	beat_sprites["quav_da"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_da.png")
	beat_sprites["quav_dc2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_dc2.png")
	beat_sprites["quav_dr"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_dr.png")
	
	beat_sprites["quav_ec"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ec.png")
	beat_sprites["quav_ed"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ed.png")
	beat_sprites["quav_ee"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ee.png")
	beat_sprites["quav_eg"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_eg.png")
	beat_sprites["quav_ea"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ea.png")
	beat_sprites["quav_ec2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ec2.png")
	beat_sprites["quav_er"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_er.png")
	
	beat_sprites["quav_gc"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_gc.png")
	beat_sprites["quav_gd"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_gd.png")
	beat_sprites["quav_ge"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ge.png")
	beat_sprites["quav_gg"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_gg.png")
	beat_sprites["quav_ga"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ga.png")
	beat_sprites["quav_gc2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_gc2.png")
	beat_sprites["quav_gr"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_gr.png")
	
	beat_sprites["quav_ac"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ac.png")
	beat_sprites["quav_ad"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ad.png")
	beat_sprites["quav_ae"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ae.png")
	beat_sprites["quav_ag"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ag.png")
	beat_sprites["quav_aa"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_aa.png")
	beat_sprites["quav_ac2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ac2.png")
	beat_sprites["quav_ar"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ar.png")
	
	beat_sprites["quav_c2c"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2c.png")
	beat_sprites["quav_c2d"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2d.png")
	beat_sprites["quav_c2e"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2e.png")
	beat_sprites["quav_c2g"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2g.png")
	beat_sprites["quav_c2a"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2a.png")
	beat_sprites["quav_c2c2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2c2.png")
	beat_sprites["quav_c2r"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_c2r.png")
	
	beat_sprites["quav_rc"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_rc.png")
	beat_sprites["quav_rd"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_rd.png")
	beat_sprites["quav_re"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_re.png")
	beat_sprites["quav_rg"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_rg.png")
	beat_sprites["quav_ra"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_ra.png")
	beat_sprites["quav_rc2"] = load("res://assets/sprites/SLOTMACHINEnotes/quav_rc2.png")

func generate_beat():
	##range affect how often certain length of notes appear. We don't want too many rests.
	var roll = randi_range(1, 100)
	##Crotchet note
	if roll <= 40:
		return [[NOTES.pick_random(),CROTCHET]]
	##Crotchet rest
	elif roll <=50:
		return [["REST",CROTCHET]]
	##Quaver note + quaver rest
	elif roll <=60: 
		return [[NOTES.pick_random(),QUAVER],["REST",QUAVER]]
	##Quaver rest + quaver note
	elif roll <=70:
		return [["REST",QUAVER],[NOTES.pick_random(),QUAVER]]
	##Quaver note + quaver note
	else:
		return [[NOTES.pick_random(),QUAVER],[NOTES.pick_random(),QUAVER]]

func generate_bar():
	var bar = []
	for i in range(4):
		bar.append(generate_beat())
	return bar
	
func beat_to_key(beat):
	if beat.size() == 1:
		return "crot_" + note_to_sprite_name(beat[0][0])
	else:
		return "quav_" + note_to_sprite_name(beat[0][0]) + note_to_sprite_name(beat[1][0])

#call the list from here always		
func bar_to_sprites(bar):
	var sprites = []
	for beat in bar:
		var key = beat_to_key(beat)
		sprites.append(beat_sprites[key])
	return sprites

func note_to_sprite_name(note):
	match note:
		"C": return "c"
		"D": return "d"
		"E": return "e"
		"G": return "g"
		"A": return "a"
		"C2": return "c2"
		"REST": return "r"
		
func play_bar(bar):
	for beat in bar:
		await play_beat(beat)

func play_bars(bars):
	for bar in bars:
		print (bar)
		await play_bar(bar)
		
func play_beat(beat):
	for note in beat:
		play_note(note)
		var duration = note[1]
		await get_tree().create_timer(duration * beat_duration()).timeout
		
func play_note(note):
		var pitch = note[0]
		if pitch != "REST":
			print(sounds[pitch])
			player.stream = sounds[pitch]
			player.play()
